site_name: Python Crash Course, Third Edition

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

theme:
  name: material
  logo: images/pcc_snake_logo.png
  favicon: images/pcc_snake_favicon-48px.png
  features:
    - navigation.indexes
    - navigation.instant

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - "Home": "index.md"
  - "What's new?": "new_in_3e.md"
  - "Solutions":
    - "solutions/index.md"
    - "Chapter 2": "solutions/chapter_2.md"
  - "Contact": "contact.md"