site_name: Python Crash Course, Third Edition

theme:
  name: material
  features:
    # - navigation.tabs
    navigation.instant

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css